version: '3'

services:

  traefik:
    image: traefik:1.6-alpine
    command: --docker --logLevel=ERROR
    labels:
      - traefik.enable=false
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  web:
    build: .
    labels:
      - traefik.backend=web
      - traefik.frontend.rule=Host:localhost
    volumes:
      - ./src:/var/www/html:rw
    environment:
      - ALLOW_OVERRIDE=true
  mysql:
    image: mysql:5.7
    labels:
      - traefik.enable=false
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_example
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./services/mysql/utf8mb4.cnf:/etc/mysql/conf.d/utf8mb4.cnf:ro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    labels:
      - traefik.backend=phpmyadmin
      - traefik.frontend.rule=Host:phpmyadmin.localhost
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    volumes:
      - phpmyadmin_data:/sessions

  mail:
    image: schickling/mailcatcher
    labels:
      - traefik.backend=mail
      - traefik.frontend.rule=Host:mail.localhost
      - traefik.port=1080

volumes:

  mysql_data:
    driver: local

  phpmyadmin_data:
    driver: local